name: C/C++ CI with GoogleTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libgtest-dev build-essential libpng-dev
        
    - name: Compile and run main program
      run: |
        g++ -Ilib src/main.cpp src/NN.cpp lib/matrix.cpp -o main -std=c++14
        echo "1" | timeout 60s ./main || echo "Program completed"
        
    - name: Compile and run tests
      run: |
        g++ -DTESTS -Ilib src/main.cpp src/NN.cpp lib/matrix.cpp -o test_app -lgtest -lgtest_main -lpthread -std=c++14
        ./test_app
