name: C/C++ CI with GoogleTest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: installation
      run: sudo apt install -y googletest libgtest-dev build-essential gcovr libpng-dev

    - name: Compile with Sigmoid activation
      run: |
        cd src
        g++ -I../lib main.cpp NN.cpp ../lib/matrix.cpp -o main_sigmoid -std=c++11

    - name: Run Sigmoid activation
      run: |
        cd src
        echo "1" | ./main_sigmoid

    - name: Compile with Tanh activation  
      run: |
        cd src
        g++ -DUSE_TANH -I../lib main.cpp NN.cpp ../lib/matrix.cpp -o main_tanh -std=c++11

    - name: Run Tanh activation
      run: |
        cd src
        echo "2" | ./main_tanh

    - name: Compile unit tests
      run: |
        cd src
        g++ -DTESTS -I../lib main.cpp NN.cpp ../lib/matrix.cpp -o test_app -lgtest -lgtest_main -lpthread -std=c++11

    - name: Run unit tests
      run: |
        cd src
        ./test_app
